name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: install lint
        run: |
          npm install eslint @eslint/js --save-dev
          npx eslint --init --yes # Use --yes to auto-generate a default config

      - name: Check style
        run: npm run eslint
